name: Feature Request
description: Suggest a new feature or improvement for Hack Club Builders.
title: "[Feature]: "
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! The more context you provide, the better.

  - type: input
    id: summary
    attributes:
      label: Feature summary
      placeholder: "Example: Add a public leaderboard for Builders XP"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      placeholder: "Example: Users can’t see who’s contributing the most"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "Example: A page showing XP earned per user, weekly/monthly"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Web / Frontend
        - API / Backend
        - Docs / Guides
        - Templates / Tools
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this hasn’t already been requested.
          required: true